drop database IF EXISTS CUGINI CASCADE;
create database CUGINI;
use CUGINI;
CREATE TABLE BADG1(C1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0015/BADG1.csv' OVERWRITE INTO TABLE BADG1;
SELECT COUNT(*) FROM CUGINI.BADG1;
