drop database IF EXISTS CUGINI CASCADE;
create database CUGINI;
use CUGINI;
CREATE TABLE VBADG2(C1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0016/VBADG2.csv' OVERWRITE INTO TABLE VBADG2;
CREATE TABLE BADG2(C1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0016/BADG2.csv' OVERWRITE INTO TABLE BADG2;
SELECT COUNT(*) FROM CUGINI.BADG2;
