drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE SIZ2_F2(F1 STRING,F2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0030/SIZ2_F2.csv' OVERWRITE INTO TABLE SIZ2_F2;
SELECT COUNT(*) FROM SIZ2_F2;
