drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE PROJ_P(PNUM STRING,PNAME STRING,PTYPE STRING,BUDGET DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0054/PROJ_P.csv' OVERWRITE INTO TABLE PROJ_P;
SELECT COUNT(*) FROM PROJ_P;
