drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE VS2(C1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0067/VS2.csv' OVERWRITE INTO TABLE VS2;
SELECT COUNT(*) FROM VS2 WHERE C1 = 1;
