drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE VSTAFF3(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0088/VSTAFF3.csv' OVERWRITE INTO TABLE VSTAFF3;
drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
SELECT COUNT(*) FROM HU.VSTAFF3;
