drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE ECCO(C1 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0182/ECCO.csv' OVERWRITE INTO TABLE ECCO;
CREATE TABLE CC(CHARTEST STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0182/CC.csv' OVERWRITE INTO TABLE CC;
SELECT CHARTEST FROM CC;
