drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE QQ(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0190/QQ.csv' OVERWRITE INTO TABLE QQ;
SELECT * FROM QQ;
