drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE JJ_20(FLOATTEST FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0246/JJ_20.csv' OVERWRITE INTO TABLE JJ_20;
CREATE TABLE JJ(FLOATTEST FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0246/JJ.csv' OVERWRITE INTO TABLE JJ;
SELECT FLOATTEST FROM JJ ORDER BY FLOATTEST DESC;
