drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TEXT240(TEXXT STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0247/TEXT240.csv' OVERWRITE INTO TABLE TEXT240;
SELECT * FROM TEXT240;
