drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE STAFF1(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0261/STAFF1.csv' OVERWRITE INTO TABLE STAFF1;
SELECT COUNT(*) FROM STAFF1;
