drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE UPUNIQ(NUMKEY DOUBLE,COL2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0265/UPUNIQ.csv' OVERWRITE INTO TABLE UPUNIQ;
SELECT MAX(NUMKEY), MIN(NUMKEY) FROM UPUNIQ;
