drop database IF EXISTS SULLIVAN1 CASCADE;
create database SULLIVAN1;
use SULLIVAN1;
CREATE TABLE MUL_SCH(EMPNUM STRING,SECOND2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0300/MUL_SCH.csv' OVERWRITE INTO TABLE MUL_SCH;
drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
SELECT EMPNUM,SECOND2 FROM SULLIVAN1.MUL_SCH ORDER BY EMPNUM;
