drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE DOMAIN_VIEW(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0410/DOMAIN_VIEW.csv' OVERWRITE INTO TABLE DOMAIN_VIEW;
SELECT COUNT(*) FROM DOMAIN_VIEW;
