drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE DUP_COL(EMP1 STRING,PNO STRING,HOURS DOUBLE,HOURS_2 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0417/DUP_COL.csv' OVERWRITE INTO TABLE DUP_COL;
SELECT EMP1, HOURS, HOURS_2 FROM DUP_COL WHERE EMP1 = 'E3';
