drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE SIZ3_P3(F1 DOUBLE,F2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0609/SIZ3_P3.csv' OVERWRITE INTO TABLE SIZ3_P3;
SELECT MAX(F1),MIN(F1) FROM SIZ3_P3;
