drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE DEPT(DNO DOUBLE,DNAME STRING,DEAN STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0637/DEPT.csv' OVERWRITE INTO TABLE DEPT;
SELECT COUNT(*) FROM DEPT WHERE DNO = 10;
