drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE JNULL3(C1 DOUBLE,D1 DOUBLE,D2 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0687/JNULL3.csv' OVERWRITE INTO TABLE JNULL3;
SELECT AVG(D1) * 10 FROM JNULL3;
