drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE WEIRDPAD(NAAM STRING,SPONSOR STRING,PADCHAR STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0700/WEIRDPAD.csv' OVERWRITE INTO TABLE WEIRDPAD;
SELECT COUNT(*) FROM WEIRDPAD A, WEIRDPAD B WHERE TRIM (LEADING '0' FROM A.SPONSOR) = TRIM (' ' FROM B.NAAM);
