drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE QUALSTAR(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0712/QUALSTAR.csv' OVERWRITE INTO TABLE QUALSTAR;
CREATE TABLE CORRQUALSTAR(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0712/CORRQUALSTAR.csv' OVERWRITE INTO TABLE CORRQUALSTAR;
SELECT COUNT(*) FROM QUALSTAR;
