drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE LUSERS(NAAM STRING,LUSER_ID DOUBLE,FILE_QUOTA DOUBLE,FILE_USAGE DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0720/LUSERS.csv' OVERWRITE INTO TABLE LUSERS;
SELECT COUNT(*) FROM LUSERS;
