drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE SSSLOG(ENTERED_BY STRING,SEVERITY DOUBLE,PROBLEM STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0726/SSSLOG.csv' OVERWRITE INTO TABLE SSSLOG;
SELECT COUNT(*) FROM SSSLOG WHERE ENTERED_BY = 'system' AND SEVERITY = 1 AND PROBLEM = 'Freed a free frag';
