drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE CH1(CH1A STRING,CH1B STRING,CH1C STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0728/CH1.csv' OVERWRITE INTO TABLE CH1;
SELECT CH1A, CH1B, CH1C FROM CH1;
