drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE TYPE_TIMES(JOB_TYPE STRING,RUN_SECONDS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0745/TYPE_TIMES.csv' OVERWRITE INTO TABLE TYPE_TIMES;
SELECT EXTRACT (SECOND FROM RUN_SECONDS) FROM TYPE_TIMES ORDER BY JOB_TYPE;
