drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NO_DUCK(GOOSE DOUBLE,ALBATROSS FLOAT,SEAGULL DOUBLE,OSPREY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0770/NO_DUCK.csv' OVERWRITE INTO TABLE NO_DUCK;
SELECT COUNT(*) FROM NO_DUCK WHERE GOOSE = 23.23;
