drop database IF EXISTS CTS2 CASCADE;
create database CTS2;
use CTS2;
CREATE TABLE PROJ_MAN(P_REF STRING,BUDGET DOUBLE,SCOPE STRING,MGR STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0823/PROJ_MAN.csv' OVERWRITE INTO TABLE PROJ_MAN;
drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
SELECT COUNT(*) FROM  CTS2.PROJ_MAN;
