drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TEST6840C(NUM_C1 DOUBLE,CH_C1 STRING,NUM_C2 DOUBLE,CH_C2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0843/TEST6840C.csv' OVERWRITE INTO TABLE TEST6840C;
SELECT  COUNT(*) FROM TEST6840C WHERE NUM_C1 = 2 AND CH_C1 = 'B' AND NUM_C2 = 2 AND CH_C2 = 'C';
