drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TAB734(CSTR1 STRING,CSTR2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0847/TAB734.csv' OVERWRITE INTO TABLE TAB734;
SELECT COUNT(CSTR1) FROM TAB734 WHERE CSTR1 <> N' * ';
