drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE V000V(DEPTNO DOUBLE,AVSAL DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0853/V000V.csv' OVERWRITE INTO TABLE V000V;
SELECT MAX(AVSAL) FROM V000V;
