drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE STAFFD(EMPNUM STRING,GRADE DOUBLE,MGR STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0867/STAFFD.csv' OVERWRITE INTO TABLE STAFFD;
SELECT COUNT (*) FROM STAFFd WHERE MGR = 'E7';
