drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TW(D STRING,E DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0888/TW.csv' OVERWRITE INTO TABLE TW;
CREATE TABLE TV(A DOUBLE,B STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0888/TV.csv' OVERWRITE INTO TABLE TV;
SELECT DISTINCT A, (SELECT D FROM TW WHERE E = X.A) FROM TV X, TW Y WHERE A = 3;
