drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TX(TX1 DOUBLE,TX2 STRING,TX3 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0901/TX.csv' OVERWRITE INTO TABLE TX;
SELECT TX1 FROM TX WHERE TX3 || TX2 IS NULL;
