drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TEXT80(TEXXT STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0927/TEXT80.csv' OVERWRITE INTO TABLE TEXT80;
CREATE TABLE T8(COL1 STRING,COL2 STRING,COL3 STRING,COL4 STRING,COL5 STRING,COL6 STRING,COL7 STRING,COL8 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0927/T8.csv' OVERWRITE INTO TABLE T8;
SELECT COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8 FROM T8;
