drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE T12(COL1 STRING,COL2 STRING,COL3 STRING,COL4 STRING,COL5 STRING,COL6 STRING,COL7 STRING,COL8 STRING,COL9 STRING,COL10 STRING,COL11 DOUBLE,COL12 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0936/T12.csv' OVERWRITE INTO TABLE T12;
SELECT COL3,COL11,COL9,COL8,COL7,COL5,COL4 FROM T12 ORDER BY COL9,COL8,COL7,COL5,COL4,COL3;
