drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TEXT240(TEXXT STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0937/TEXT240.csv' OVERWRITE INTO TABLE TEXT240;
CREATE TABLE T240(STR240 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0937/T240.csv' OVERWRITE INTO TABLE T240;
SELECT * FROM T240;
