drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE II(DOUBLETEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0960/II.csv' OVERWRITE INTO TABLE II;
SELECT COUNT(*) FROM II WHERE DOUBLETEST > -0.1073741824 AND DOUBLETEST < -0.1073741822;
