drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE SIZ2_F10(F1 DOUBLE,F2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0970/SIZ2_F10.csv' OVERWRITE INTO TABLE SIZ2_F10;
SELECT COUNT(*) FROM SIZ2_F10;
