drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE UUSIG(U1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0986/UUSIG.csv' OVERWRITE INTO TABLE UUSIG;
CREATE TABLE UUUSIG(IRREVERENT DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/0986/UUUSIG.csv' OVERWRITE INTO TABLE UUUSIG;
SELECT COUNT(DISTINCT U1) FROM UUSIG;
