drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE C_TRANSACTION(COMMOD_NO DOUBLE,TOT_PRICE DOUBLE,CURRENCY STRING,UNITS DOUBLE,MEASURE STRING,T_DATE DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/1035/C_TRANSACTION.csv' OVERWRITE INTO TABLE C_TRANSACTION;
SELECT COUNT(*) FROM C_TRANSACTION WHERE COMMOD_NO = 17;
