--having
drop database IF EXISTS Panthera CASCADE;
create database Panthera;
use Panthera;
CREATE TABLE WORKS(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/panthera/WORKS.csv' OVERWRITE INTO TABLE WORKS;
CREATE TABLE STAFF(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/panthera/STAFF.csv' OVERWRITE INTO TABLE STAFF;
CREATE TABLE PROJ(PNUM STRING,PNAME STRING,PTYPE STRING,BUDGET DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH 'src/test/resources/plusd/panthera/PROJ.csv' OVERWRITE INTO TABLE PROJ;
SELECT STAFF.EMPNUM, AVG(GRADE), STAFF.CITY FROM STAFF GROUP BY STAFF.CITY, STAFF.EMPNUM HAVING SUM(GRADE) < ANY (SELECT STAFF.GRADE FROM STAFF WHERE STAFF.GRADE >= 12 GROUP BY STAFF.EMPNUM, STAFF.GRADE);
