drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE NN(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0188/NN.csv' OVERWRITE INTO TABLE NN;
SELECT * FROM NN;
