drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TEMP_OBSERV(YEAR_OBSERV DOUBLE,CITY STRING,MAX_TEMP DOUBLE,MIN_TEMP DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0380/TEMP_OBSERV.csv' OVERWRITE INTO TABLE TEMP_OBSERV;
SELECT COUNT(*) FROM TEMP_OBSERV WHERE MAX_TEMP = 123.45 AND MAX_TEMP NOT BETWEEN 123.4516 AND 123.4518;
