drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE WHICH_SCHEMA1(C1 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0386/WHICH_SCHEMA1.csv' OVERWRITE INTO TABLE WHICH_SCHEMA1;
SELECT C1 FROM WHICH_SCHEMA1;
