drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE MULTI_YEAR_OBSERV(CITY STRING,HIGH DOUBLE,LOW DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0414/MULTI_YEAR_OBSERV.csv' OVERWRITE INTO TABLE MULTI_YEAR_OBSERV;
SELECT CITY, HIGH, LOW FROM MULTI_YEAR_OBSERV ORDER BY CITY ASC;
