drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE STAFF6_WITH_GRADES(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0634/STAFF6_WITH_GRADES.csv' OVERWRITE INTO TABLE STAFF6_WITH_GRADES;
CREATE TABLE STAFF6(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0634/STAFF6.csv' OVERWRITE INTO TABLE STAFF6;
SELECT EMPNAME FROM STAFF6 WHERE GRADE IS NULL;
