drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE WORKWEEK(EMPNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0706/WORKWEEK.csv' OVERWRITE INTO TABLE WORKWEEK;
SELECT EMPNUM, SUM (HOURS) FROM WORKWEEK WHERE HOURS > 20 GROUP BY EMPNUM HAVING EMPNUM = 'E1';
