drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE GRANT010(C1 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0794/GRANT010.csv' OVERWRITE INTO TABLE GRANT010;
drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
SELECT COUNT(*) FROM FLATER.GRANT010;
