drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TAB735(C1 DOUBLE,C2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0849/TAB735.csv' OVERWRITE INTO TABLE TAB735;
SELECT C1,C2 FROM CTS1.TAB735 ORDER BY C1;
