drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE JJ_20(FLOATTEST FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0952/JJ_20.csv' OVERWRITE INTO TABLE JJ_20;
CREATE TABLE JJ(FLOATTEST FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0952/JJ.csv' OVERWRITE INTO TABLE JJ;
SELECT COUNT(*) FROM JJ WHERE FLOATTEST > -0.1048576 AND FLOATTEST < -0.1048574;
