drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE SIZ3_F(P1 STRING,P2 STRING,P3 DOUBLE,P4 STRING,P5 DOUBLE,P6 STRING,P7 STRING,P8 DOUBLE,P9 DOUBLE,P10 DOUBLE,P11 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0984/SIZ3_F.csv' OVERWRITE INTO TABLE SIZ3_F;
SELECT COUNT(*) FROM SIZ3_F WHERE P1 = '  A';
