--having
drop database IF EXISTS Panthera CASCADE;
create database Panthera;
use Panthera;
CREATE TABLE WORKS(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/panthera/WORKS.csv' OVERWRITE INTO TABLE WORKS;
CREATE TABLE STAFF(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/panthera/STAFF.csv' OVERWRITE INTO TABLE STAFF;
CREATE TABLE PROJ(PNUM STRING,PNAME STRING,PTYPE STRING,BUDGET DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/panthera/PROJ.csv' OVERWRITE INTO TABLE PROJ;
SELECT STAFF.EMPNUM FROM STAFF GROUP BY STAFF.EMPNUM HAVING EXISTS (SELECT * FROM WORKS WHERE WORKS.HOURS > 60);
