drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TMP(T1 STRING,T2 DOUBLE,T3 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0115/TMP.csv' OVERWRITE INTO TABLE TMP;
SELECT * FROM   TMP WHERE  T2 IS NULL;
