drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE NEXTKEY(KEYNUM DOUBLE,AUTHOR STRING,DOLLARS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
CREATE TABLE LL(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0242/LL.csv' OVERWRITE INTO TABLE LL;
CREATE TABLE HH(SMALLTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
SELECT * FROM LL;
