drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE STAFF1(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0263/STAFF1.csv' OVERWRITE INTO TABLE STAFF1;
SELECT SUM(GRADE) FROM STAFF1;
