drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE UPUNIQ(NUMKEY DOUBLE,COL2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0532/UPUNIQ.csv' OVERWRITE INTO TABLE UPUNIQ;
drop database IF EXISTS SULLIVAN CASCADE;
create database SULLIVAN;
use SULLIVAN;
SELECT * FROM HU.UPUNIQ WHERE NUMKEY = 3;
