drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NMGRP3(NAME STRING,GRP DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0663/NMGRP3.csv' OVERWRITE INTO TABLE NMGRP3;
SELECT COUNT(*) FROM NMGRP3;
