drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE ABOVE_AVERAGE(COLUMN_1 STRING,COLUMN_2 DOUBLE,COLUMN_3 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0672/ABOVE_AVERAGE.csv' OVERWRITE INTO TABLE ABOVE_AVERAGE;
SELECT * FROM ABOVE_AVERAGE ORDER BY COLUMN_1;
