drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE PTypes(TYPE STRING,NUM DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0742/PTypes.csv' OVERWRITE INTO TABLE PTypes;
SELECT * FROM PTYPES ORDER BY NUM;
