drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE SEVEN_TYPES(T_INT DOUBLE,T_CHAR STRING,T_SMALL DOUBLE,T_DECIMAL DOUBLE,T_REAL FLOAT,T_FLOAT FLOAT,T_DOUBLE FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0767/SEVEN_TYPES.csv' OVERWRITE INTO TABLE SEVEN_TYPES;
SELECT XX.T_INT, YY.T_INT FROM SEVEN_TYPES XX RIGHT OUTER JOIN SEVEN_TYPES YY ON XX.T_INT = YY.T_INT +1 ORDER BY YY.T_INT;
