drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE CTRANS(WIN_COUNT DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0788/CTRANS.csv' OVERWRITE INTO TABLE CTRANS;
SELECT * FROM CTRANS;
