drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TEST6840B(NUM_B DOUBLE,CH_B STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0845/TEST6840B.csv' OVERWRITE INTO TABLE TEST6840B;
CREATE TABLE TEST6840A(NUM_A DOUBLE,CH_A STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0845/TEST6840A.csv' OVERWRITE INTO TABLE TEST6840A;
SELECT * FROM (TEST6840B FULL JOIN TEST6840A CN1 ON TEST6840B.CH_B = CN1.CH_A) FULL JOIN TEST6840A CN2 ON TEST6840B.NUM_B = CN2.NUM_A ORDER BY TEST6840B.NUM_B, CN1.NUM_A;
