drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE STAFFA(HOURS DOUBLE,SALARY DOUBLE,EMPNUM STRING,PNUM DOUBLE,EMPNAME STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0879/STAFFA.csv' OVERWRITE INTO TABLE STAFFA;
SELECT COUNT (*) FROM CTS1.STAFFa;
