drop database IF EXISTS SULLIVAN CASCADE;
create database SULLIVAN;
use SULLIVAN;
CREATE TABLE WORKS_P(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0056/WORKS_P.csv' OVERWRITE INTO TABLE WORKS_P;
SELECT COUNT(*) FROM WORKS_P;
