drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE TMP(T1 STRING,T2 DOUBLE,T3 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0113/TMP.csv' OVERWRITE INTO TABLE TMP;
SELECT * FROM TMP WHERE T2 = 23 AND T3 = 'xxxx';
