drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE DD(CHARTEST STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0183/DD.csv' OVERWRITE INTO TABLE DD;
SELECT CHARTEST FROM DD;
