drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE EE(INTTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0184/EE.csv' OVERWRITE INTO TABLE EE;
SELECT INTTEST FROM EE;
