drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE RR(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0191/RR.csv' OVERWRITE INTO TABLE RR;
SELECT * FROM RR;
