drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE KK(FLOATTEST FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0241/KK.csv' OVERWRITE INTO TABLE KK;
SELECT * FROM KK WHERE FLOATTEST > 123456.123450 and FLOATTEST < 123456.123462;
