drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE PROJ1(PNUM STRING,PNAME STRING,PTYPE STRING,BUDGET DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0266/PROJ1.csv' OVERWRITE INTO TABLE PROJ1;
SELECT CITY FROM PROJ1 WHERE PNUM = 'P1';
