drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE T4(STR110 STRING,NUM6 DOUBLE,COL3 STRING,COL4 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0270/T4.csv' OVERWRITE INTO TABLE T4;
SELECT COUNT(*) FROM T4 WHERE STR110 LIKE '%HU%';
