drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE MM2(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0359/MM2.csv' OVERWRITE INTO TABLE MM2;
CREATE TABLE MM(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0359/MM.csv' OVERWRITE INTO TABLE MM;
SELECT NUMTEST FROM MM;
