drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE STAFFV2_VIEW(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0406/STAFFV2_VIEW.csv' OVERWRITE INTO TABLE STAFFV2_VIEW;
SELECT EMPNUM, GRADE FROM STAFFV2_VIEW WHERE EMPNUM = 'E3';
