drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE DOMAIN_VIEW(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0408/DOMAIN_VIEW.csv' OVERWRITE INTO TABLE DOMAIN_VIEW;
SELECT EMPNUM, HOURS FROM DOMAIN_VIEW WHERE PNUM = 'P3';
