drop database IF EXISTS SCHANZLE CASCADE;
create database SCHANZLE;
use SCHANZLE;
CREATE TABLE CPREF(KCR DOUBLE,JUNK2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0418/CPREF.csv' OVERWRITE INTO TABLE CPREF;
CREATE TABLE CPBASE(KC DOUBLE,JUNK1 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0418/CPBASE.csv' OVERWRITE INTO TABLE CPBASE;
SELECT COUNT(*) FROM CPBASE, CPREF;
