drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE WORKS3(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0579/WORKS3.csv' OVERWRITE INTO TABLE WORKS3;
CREATE TABLE WORKS(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0579/WORKS.csv' OVERWRITE INTO TABLE WORKS;
SELECT COUNT(*) FROM WORKS WHERE EMPNUM = 'E1';
