drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE STAFF_M(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING,PRI_WK STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0595/STAFF_M.csv' OVERWRITE INTO TABLE STAFF_M;
SELECT COUNT(*) FROM STAFF_M WHERE PRI_WK = 'P9';
