drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE SIZ2_F3(F1 DOUBLE,F2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0610/SIZ2_F3.csv' OVERWRITE INTO TABLE SIZ2_F3;
SELECT MAX(F1),MIN(F1) FROM SIZ2_F3;
