drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE CHAR_DEFAULT(SEX_CODE STRING,NICKNAME STRING,INSURANCE1 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0615/CHAR_DEFAULT.csv' OVERWRITE INTO TABLE CHAR_DEFAULT;
SELECT NICKNAME, INSURANCE1 FROM CHAR_DEFAULT WHERE SEX_CODE = 'M';
