drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE APPROX_DEF(X_COUNT FLOAT,Y_COUNT FLOAT,Z_COUNT FLOAT,ZZ_COUNT FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0618/APPROX_DEF.csv' OVERWRITE INTO TABLE APPROX_DEF;
SELECT COUNT(*) FROM APPROX_DEF WHERE (Y_COUNT BETWEEN -9.991E10 AND -9.989E10) AND (Z_COUNT BETWEEN 3.44E-11 AND 3.46E-11) AND (ZZ_COUNT BETWEEN -7.6778E-7 AND -7.6776E-7) OR (X_COUNT BETWEEN 1.77E12 AND 1.79E12);
