drop database IF EXISTS SUN CASCADE;
create database SUN;
use SUN;
CREATE TABLE DEPT(DNO DOUBLE,DNAME STRING,DEAN STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0638/DEPT.csv' OVERWRITE INTO TABLE DEPT;
SELECT * FROM DEPT ORDER BY DNO;
