drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE ICAST2(C1 DOUBLE,C2 FLOAT,C3 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0640/ICAST2.csv' OVERWRITE INTO TABLE ICAST2;
SELECT C1, C2, C3 FROM ICAST2;
