drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NAMGRP1(EMPNUM DOUBLE,NAME STRING,GRP DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0644/NAMGRP1.csv' OVERWRITE INTO TABLE NAMGRP1;
SELECT EMPNUM FROM NAMGRP1 WHERE NAME = 'KERI' AND GRP = 10;
