drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NAMGRP3(EMPNUM DOUBLE,NAME STRING,GRP DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0653/NAMGRP3.csv' OVERWRITE INTO TABLE NAMGRP3;
SELECT COUNT(*) FROM NAMGRP3 WHERE EMPNUM = 1 AND NAME = 'MARY' AND GRP = 20;
