drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NAMGRP4(EMPNUM DOUBLE,NAME STRING,GRP DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0664/NAMGRP4.csv' OVERWRITE INTO TABLE NAMGRP4;
SELECT COUNT(*) FROM NAMGRP4 WHERE EMPNUM = 0 AND NAME = 'KERI' AND GRP = 10;
