drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE JNULL3(C1 DOUBLE,D1 DOUBLE,D2 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0686/JNULL3.csv' OVERWRITE INTO TABLE JNULL3;
SELECT COUNT(*) FROM JNULL3 WHERE D2 IS NULL;
