drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE CHANGGVIEW(NAAM STRING,AGE DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0691/CHANGGVIEW.csv' OVERWRITE INTO TABLE CHANGGVIEW;
SELECT MAX(AGE) FROM CHANGGVIEW;
