drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE LUSER_DATA(FILE_NAME STRING,LUSER_ID DOUBLE,LUSER_DATA STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0719/LUSER_DATA.csv' OVERWRITE INTO TABLE LUSER_DATA;
SELECT COUNT(*) FROM LUSER_DATA;
