drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE STANDARD_INPUT(USER_NAME STRING,USER_INPUT DOUBLE,RECEIVABLE FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0722/STANDARD_INPUT.csv' OVERWRITE INTO TABLE STANDARD_INPUT;
SELECT AVG (USER_INPUT) FROM STANDARD_INPUT;
