drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE SSSLOG(ENTERED_BY STRING,SEVERITY DOUBLE,PROBLEM STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0727/SSSLOG.csv' OVERWRITE INTO TABLE SSSLOG;
SELECT COUNT(*) FROM SSSLOG WHERE ENTERED_BY = 'nobody' AND SEVERITY = 6 AND PROBLEM IS NULL;
