drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE CH1(CH1A STRING,CH1B STRING,CH1C STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0729/CH1.csv' OVERWRITE INTO TABLE CH1;
SELECT CH1A, CH1B, CH1C FROM CH1;
