drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE VERBOSE_INV(ITEMTEXT STRING,CONDTEXT STRING,COSTTEXT STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0736/VERBOSE_INV.csv' OVERWRITE INTO TABLE VERBOSE_INV;
SELECT COUNT(*) FROM VERBOSE_INV WHERE ITEMTEXT = 'Lousy excuse for a tape deck' AND CONDTEXT = 'Visibly damaged (no returns)' AND COSTTEXT = 'Expensive';
