drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE PROJ_HOURS(PNUM STRING,HOURS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0744/PROJ_HOURS.csv' OVERWRITE INTO TABLE PROJ_HOURS;
SELECT EXTRACT (HOUR FROM HOURS), EXTRACT (MINUTE FROM HOURS) FROM PROJ_HOURS ORDER BY PNUM;
