drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE ECCO(C1 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0769/ECCO.csv' OVERWRITE INTO TABLE ECCO;
drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
SELECT CAST (100.5 AS DECIMAL (3)) FROM HU.ECCO;
