drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE NO_DUCK(GOOSE DOUBLE,ALBATROSS FLOAT,SEAGULL DOUBLE,OSPREY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0785/NO_DUCK.csv' OVERWRITE INTO TABLE NO_DUCK;
SELECT CAST (GOOSE AS INT) FROM NO_DUCK;
