drop database IF EXISTS FLATER CASCADE;
create database FLATER;
use FLATER;
CREATE TABLE XX(C1 STRING,C2 STRING,C3 STRING,C4 STRING,C5 TIMESTAMP,C6 FLOAT,C7 FLOAT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0791/XX.csv' OVERWRITE INTO TABLE XX;
SELECT COUNT(*) FROM XX WHERE C4 = 'Timestamp' AND C5 BETWEEN TIMESTAMP '1993-11-10 00:01:00' AND TIMESTAMP '1993-11-10 00:03:00';
