drop database IF EXISTS CTS1 CASCADE;
create database CTS1;
use CTS1;
CREATE TABLE TAB734(CSTR1 STRING,CSTR2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0846/TAB734.csv' OVERWRITE INTO TABLE TAB734;
SELECT COUNT(*) FROM TAB734 WHERE CSTR1 = CSTR2;
