drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE HH(SMALLTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0940/HH.csv' OVERWRITE INTO TABLE HH;
SELECT COUNT(*) FROM HH WHERE SMALLTEST = 9999;
