drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE PP_15(NUMTEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0946/PP_15.csv' OVERWRITE INTO TABLE PP_15;
SELECT COUNT(*) FROM PP_15 WHERE NUMTEST = -0.912345678901234;
