drop database IF EXISTS HU CASCADE;
create database HU;
use HU;
CREATE TABLE II(DOUBLETEST DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/0958/II.csv' OVERWRITE INTO TABLE II;
SELECT COUNT(*) FROM II WHERE DOUBLETEST > 0.1073741822 AND DOUBLETEST < 0.1073741824;
