drop database IF EXISTS MCGINN CASCADE;
create database MCGINN;
use MCGINN;
CREATE TABLE VIEWABCDEFGHIKLMN19(COL3 DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/1028/VIEWABCDEFGHIKLMN19.csv' OVERWRITE INTO TABLE VIEWABCDEFGHIKLMN19;
SELECT COL3                 FROM  VIEWABCDEFGHIKLMN19;
