--having,and,multi_level_subq
drop database IF EXISTS Panthera CASCADE;
create database Panthera;
use Panthera;
CREATE TABLE WORKS(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/panthera/WORKS.csv' OVERWRITE INTO TABLE WORKS;
CREATE TABLE STAFF(EMPNUM STRING,EMPNAME STRING,GRADE DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/panthera/STAFF.csv' OVERWRITE INTO TABLE STAFF;
CREATE TABLE PROJ(PNUM STRING,PNAME STRING,PTYPE STRING,BUDGET DOUBLE,CITY STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '/home/cherry/sotc_cloud-panthera-nist-test/plusd/panthera/PROJ.csv' OVERWRITE INTO TABLE PROJ;
SELECT PNUM, PTYPE FROM PROJ GROUP BY PTYPE, PNUM HAVING PROJ.PNUM BETWEEN (SELECT MIN(PNUM) FROM WORKS WHERE WORKS.EMPNUM < 'E2') AND (SELECT MAX(PNUM) FROM WORKS, STAFF WHERE WORKS.EMPNUM > STAFF.EMPNUM AND WORKS.HOURS != 80);
