| Deale           | P1  | 
| Deale           | P1  | 
| Vienna          | P2  | 
| Vienna          | P2  | 
| Deale           | P4  | 
| Deale           | P4  | 
| Vienna          | P5  | 
| Vienna          | P5  | 
| Toyko           | P6  | 
| Toyko           | P6  | 
| Deale           | P7  | 
| Deale           | P7  | 
| Seoul           | P8  | 
