| E1  | Alice                | 12 | Deale           | 
| E6  | Alpha                | 7 | NULL | 
| E2  | Betty                | 10 | Vienna          | 
| E3  | Carmen               | 13 | Vienna          | 
| E4  | Don                  | 12 | Deale           | 
| E5  | Ed                   | 13 | Akron           | 
| E9  | Frank                | NULL | Toyko           | 
| E11 | James                | 4 | Seoul           | 
| E8  | Lucia                | 20 | NULL | 
| E10 | NULL | 3 | NULL | 
| E7  | NULL | 16 | Toyko           | 
