| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E3  | P2  | 20 | 
| E3  | Carmen               | 13 | Vienna          | E3  | P2  | 20 | 
| E3  | Carmen               | 13 | Vienna          | E3  | P2  | 20 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P5  | NULL | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P5  | NULL | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
| E6  | Alpha                | 7 | NULL | E6  | P3  | NULL | 
| E6  | Alpha                | 7 | NULL | E6  | P6  | 100 | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
| E7  | NULL | 16 | Toyko           | E7  | P7  | 5 | 
| E7  | NULL | 16 | Toyko           | E7  | P1  | 200 | 
| E7  | NULL | 16 | Toyko           | E7  | P5  | 45 | 
