| E1  | Alice                | 12 | Deale           | E1  | P1  | 40 | 
| E1  | Alice                | 12 | Deale           | E1  | P2  | 20 | 
| E1  | Alice                | 12 | Deale           | E1  | P6  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P5  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P6  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P5  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P4  | 20 | 
| E1  | Alice                | 12 | Deale           | E1  | P3  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E2  | P2  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E6  | P6  | 100 | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
