| E1  | Alice                | 12 | Deale           | E1  | P2  | 20 | 
| E1  | Alice                | 12 | Deale           | E1  | P3  | 80 | 
| E1  | Alice                | 12 | Deale           | E1  | P4  | 20 | 
| E1  | Alice                | 12 | Deale           | E1  | P5  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P6  | 12 | 
| E1  | Alice                | 12 | Deale           | E2  | P2  | 80 | 
| E1  | Alice                | 12 | Deale           | E3  | P2  | 20 | 
| E1  | Alice                | 12 | Deale           | E4  | P2  | NULL | 
| E1  | Alice                | 12 | Deale           | E4  | P4  | 40 | 
| E1  | Alice                | 12 | Deale           | E4  | P5  | 62 | 
| E1  | Alice                | 12 | Deale           | E4  | P6  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P7  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P6  | 150 | 
| E1  | Alice                | 12 | Deale           | E5  | P5  | NULL | 
| E1  | Alice                | 12 | Deale           | E6  | P3  | NULL | 
| E1  | Alice                | 12 | Deale           | E6  | P6  | 100 | 
| E1  | Alice                | 12 | Deale           | E7  | P7  | 5 | 
| E1  | Alice                | 12 | Deale           | E7  | P5  | 45 | 
| E1  | Alice                | 12 | Deale           | E1  | P5  | 12 | 
| E1  | Alice                | 12 | Deale           | E1  | P6  | 12 | 
| E1  | Alice                | 12 | Deale           | E2  | P2  | 80 | 
| E1  | Alice                | 12 | Deale           | E3  | P2  | 20 | 
| E1  | Alice                | 12 | Deale           | E4  | P2  | NULL | 
| E1  | Alice                | 12 | Deale           | E4  | P4  | 40 | 
| E1  | Alice                | 12 | Deale           | E4  | P5  | 62 | 
| E1  | Alice                | 12 | Deale           | E4  | P6  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P7  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P7  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P6  | 150 | 
| E1  | Alice                | 12 | Deale           | E5  | P5  | NULL | 
| E1  | Alice                | 12 | Deale           | E2  | P2  | 80 | 
| E1  | Alice                | 12 | Deale           | E3  | P2  | 20 | 
| E1  | Alice                | 12 | Deale           | E4  | P2  | NULL | 
| E1  | Alice                | 12 | Deale           | E4  | P4  | 40 | 
| E1  | Alice                | 12 | Deale           | E4  | P5  | 62 | 
| E1  | Alice                | 12 | Deale           | E4  | P6  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P7  | 80 | 
| E1  | Alice                | 12 | Deale           | E5  | P7  | 80 | 
| E2  | Betty                | 10 | Vienna          | E1  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E1  | P3  | 80 | 
| E2  | Betty                | 10 | Vienna          | E1  | P4  | 20 | 
| E2  | Betty                | 10 | Vienna          | E1  | P5  | 12 | 
| E2  | Betty                | 10 | Vienna          | E1  | P6  | 12 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P4  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P5  | 62 | 
| E2  | Betty                | 10 | Vienna          | E4  | P6  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P7  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P6  | 150 | 
| E2  | Betty                | 10 | Vienna          | E5  | P5  | NULL | 
| E2  | Betty                | 10 | Vienna          | E6  | P1  | 80 | 
| E2  | Betty                | 10 | Vienna          | E6  | P3  | NULL | 
| E2  | Betty                | 10 | Vienna          | E6  | P6  | 100 | 
| E2  | Betty                | 10 | Vienna          | E7  | P7  | 5 | 
| E2  | Betty                | 10 | Vienna          | E7  | P1  | 200 | 
| E2  | Betty                | 10 | Vienna          | E7  | P5  | 45 | 
| E2  | Betty                | 10 | Vienna          | E1  | P5  | 12 | 
| E2  | Betty                | 10 | Vienna          | E1  | P6  | 12 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P4  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P5  | 62 | 
| E2  | Betty                | 10 | Vienna          | E4  | P6  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P7  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P7  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P6  | 150 | 
| E2  | Betty                | 10 | Vienna          | E5  | P5  | NULL | 
| E2  | Betty                | 10 | Vienna          | E6  | P1  | 80 | 
| E2  | Betty                | 10 | Vienna          | E2  | P1  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P4  | 40 | 
| E2  | Betty                | 10 | Vienna          | E4  | P5  | 62 | 
| E2  | Betty                | 10 | Vienna          | E4  | P6  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P7  | 80 | 
| E2  | Betty                | 10 | Vienna          | E5  | P7  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P1  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P3  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P4  | 20 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P5  | 12 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P6  | 12 | 
| E3  | Carmen               | 13 | Vienna          | E2  | P1  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P4  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P5  | 62 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P6  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P7  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P6  | 150 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P5  | NULL | 
| E3  | Carmen               | 13 | Vienna          | E6  | P1  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E6  | P3  | NULL | 
| E3  | Carmen               | 13 | Vienna          | E6  | P6  | 100 | 
| E3  | Carmen               | 13 | Vienna          | E7  | P7  | 5 | 
| E3  | Carmen               | 13 | Vienna          | E7  | P1  | 200 | 
| E3  | Carmen               | 13 | Vienna          | E7  | P5  | 45 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P5  | 12 | 
| E3  | Carmen               | 13 | Vienna          | E1  | P6  | 12 | 
| E3  | Carmen               | 13 | Vienna          | E2  | P1  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P4  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P5  | 62 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P6  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P7  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P7  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P6  | 150 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P5  | NULL | 
| E3  | Carmen               | 13 | Vienna          | E6  | P1  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E2  | P1  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P4  | 40 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P5  | 62 | 
| E3  | Carmen               | 13 | Vienna          | E4  | P6  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P7  | 80 | 
| E3  | Carmen               | 13 | Vienna          | E5  | P7  | 80 | 
| E4  | Don                  | 12 | Deale           | E1  | P2  | 20 | 
| E4  | Don                  | 12 | Deale           | E1  | P3  | 80 | 
| E4  | Don                  | 12 | Deale           | E1  | P4  | 20 | 
| E4  | Don                  | 12 | Deale           | E1  | P5  | 12 | 
| E4  | Don                  | 12 | Deale           | E1  | P6  | 12 | 
| E4  | Don                  | 12 | Deale           | E2  | P2  | 80 | 
| E4  | Don                  | 12 | Deale           | E3  | P2  | 20 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P7  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P6  | 150 | 
| E4  | Don                  | 12 | Deale           | E5  | P5  | NULL | 
| E4  | Don                  | 12 | Deale           | E6  | P3  | NULL | 
| E4  | Don                  | 12 | Deale           | E6  | P6  | 100 | 
| E4  | Don                  | 12 | Deale           | E7  | P7  | 5 | 
| E4  | Don                  | 12 | Deale           | E7  | P5  | 45 | 
| E4  | Don                  | 12 | Deale           | E1  | P5  | 12 | 
| E4  | Don                  | 12 | Deale           | E1  | P6  | 12 | 
| E4  | Don                  | 12 | Deale           | E2  | P2  | 80 | 
| E4  | Don                  | 12 | Deale           | E3  | P2  | 20 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P7  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P7  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P6  | 150 | 
| E4  | Don                  | 12 | Deale           | E5  | P5  | NULL | 
| E4  | Don                  | 12 | Deale           | E2  | P2  | 80 | 
| E4  | Don                  | 12 | Deale           | E3  | P2  | 20 | 
| E4  | Don                  | 12 | Deale           | E4  | P2  | NULL | 
| E4  | Don                  | 12 | Deale           | E4  | P4  | 40 | 
| E4  | Don                  | 12 | Deale           | E4  | P5  | 62 | 
| E4  | Don                  | 12 | Deale           | E4  | P6  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P7  | 80 | 
| E4  | Don                  | 12 | Deale           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E1  | P1  | 40 | 
| E5  | Ed                   | 13 | Akron           | E1  | P2  | 20 | 
| E5  | Ed                   | 13 | Akron           | E1  | P3  | 80 | 
| E5  | Ed                   | 13 | Akron           | E1  | P4  | 20 | 
| E5  | Ed                   | 13 | Akron           | E1  | P5  | 12 | 
| E5  | Ed                   | 13 | Akron           | E1  | P6  | 12 | 
| E5  | Ed                   | 13 | Akron           | E2  | P1  | 40 | 
| E5  | Ed                   | 13 | Akron           | E2  | P2  | 80 | 
| E5  | Ed                   | 13 | Akron           | E3  | P2  | 20 | 
| E5  | Ed                   | 13 | Akron           | E4  | P2  | NULL | 
| E5  | Ed                   | 13 | Akron           | E4  | P4  | 40 | 
| E5  | Ed                   | 13 | Akron           | E4  | P5  | 62 | 
| E5  | Ed                   | 13 | Akron           | E4  | P6  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P5  | NULL | 
| E5  | Ed                   | 13 | Akron           | E6  | P1  | 80 | 
| E5  | Ed                   | 13 | Akron           | E6  | P3  | NULL | 
| E5  | Ed                   | 13 | Akron           | E6  | P6  | 100 | 
| E5  | Ed                   | 13 | Akron           | E7  | P7  | 5 | 
| E5  | Ed                   | 13 | Akron           | E7  | P1  | 200 | 
| E5  | Ed                   | 13 | Akron           | E7  | P5  | 45 | 
| E5  | Ed                   | 13 | Akron           | E1  | P5  | 12 | 
| E5  | Ed                   | 13 | Akron           | E1  | P6  | 12 | 
| E5  | Ed                   | 13 | Akron           | E2  | P1  | 40 | 
| E5  | Ed                   | 13 | Akron           | E2  | P2  | 80 | 
| E5  | Ed                   | 13 | Akron           | E3  | P2  | 20 | 
| E5  | Ed                   | 13 | Akron           | E4  | P2  | NULL | 
| E5  | Ed                   | 13 | Akron           | E4  | P4  | 40 | 
| E5  | Ed                   | 13 | Akron           | E4  | P5  | 62 | 
| E5  | Ed                   | 13 | Akron           | E4  | P6  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P6  | 150 | 
| E5  | Ed                   | 13 | Akron           | E5  | P5  | NULL | 
| E5  | Ed                   | 13 | Akron           | E6  | P1  | 80 | 
| E5  | Ed                   | 13 | Akron           | E2  | P1  | 40 | 
| E5  | Ed                   | 13 | Akron           | E2  | P2  | 80 | 
| E5  | Ed                   | 13 | Akron           | E3  | P2  | 20 | 
| E5  | Ed                   | 13 | Akron           | E4  | P2  | NULL | 
| E5  | Ed                   | 13 | Akron           | E4  | P4  | 40 | 
| E5  | Ed                   | 13 | Akron           | E4  | P5  | 62 | 
| E5  | Ed                   | 13 | Akron           | E4  | P6  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E5  | Ed                   | 13 | Akron           | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E1  | P1  | 40 | 
| E6  | Alpha                | 7 | NULL | E1  | P2  | 20 | 
| E6  | Alpha                | 7 | NULL | E1  | P3  | 80 | 
| E6  | Alpha                | 7 | NULL | E1  | P4  | 20 | 
| E6  | Alpha                | 7 | NULL | E1  | P5  | 12 | 
| E6  | Alpha                | 7 | NULL | E1  | P6  | 12 | 
| E6  | Alpha                | 7 | NULL | E2  | P1  | 40 | 
| E6  | Alpha                | 7 | NULL | E2  | P2  | 80 | 
| E6  | Alpha                | 7 | NULL | E3  | P2  | 20 | 
| E6  | Alpha                | 7 | NULL | E4  | P2  | NULL | 
| E6  | Alpha                | 7 | NULL | E4  | P4  | 40 | 
| E6  | Alpha                | 7 | NULL | E4  | P5  | 62 | 
| E6  | Alpha                | 7 | NULL | E4  | P6  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P6  | 150 | 
| E6  | Alpha                | 7 | NULL | E5  | P5  | NULL | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
| E6  | Alpha                | 7 | NULL | E6  | P3  | NULL | 
| E6  | Alpha                | 7 | NULL | E6  | P6  | 100 | 
| E6  | Alpha                | 7 | NULL | E7  | P7  | 5 | 
| E6  | Alpha                | 7 | NULL | E7  | P1  | 200 | 
| E6  | Alpha                | 7 | NULL | E7  | P5  | 45 | 
| E6  | Alpha                | 7 | NULL | E1  | P5  | 12 | 
| E6  | Alpha                | 7 | NULL | E1  | P6  | 12 | 
| E6  | Alpha                | 7 | NULL | E2  | P1  | 40 | 
| E6  | Alpha                | 7 | NULL | E2  | P2  | 80 | 
| E6  | Alpha                | 7 | NULL | E3  | P2  | 20 | 
| E6  | Alpha                | 7 | NULL | E4  | P2  | NULL | 
| E6  | Alpha                | 7 | NULL | E4  | P4  | 40 | 
| E6  | Alpha                | 7 | NULL | E4  | P5  | 62 | 
| E6  | Alpha                | 7 | NULL | E4  | P6  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P6  | 150 | 
| E6  | Alpha                | 7 | NULL | E5  | P5  | NULL | 
| E6  | Alpha                | 7 | NULL | E6  | P1  | 80 | 
| E6  | Alpha                | 7 | NULL | E2  | P1  | 40 | 
| E6  | Alpha                | 7 | NULL | E2  | P2  | 80 | 
| E6  | Alpha                | 7 | NULL | E3  | P2  | 20 | 
| E6  | Alpha                | 7 | NULL | E4  | P2  | NULL | 
| E6  | Alpha                | 7 | NULL | E4  | P4  | 40 | 
| E6  | Alpha                | 7 | NULL | E4  | P5  | 62 | 
| E6  | Alpha                | 7 | NULL | E4  | P6  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P7  | 80 | 
| E6  | Alpha                | 7 | NULL | E5  | P7  | 80 | 
| E7  | NULL | 16 | Toyko           | E1  | P1  | 40 | 
| E7  | NULL | 16 | Toyko           | E1  | P2  | 20 | 
| E7  | NULL | 16 | Toyko           | E1  | P3  | 80 | 
| E7  | NULL | 16 | Toyko           | E1  | P4  | 20 | 
| E7  | NULL | 16 | Toyko           | E1  | P5  | 12 | 
| E7  | NULL | 16 | Toyko           | E2  | P1  | 40 | 
| E7  | NULL | 16 | Toyko           | E2  | P2  | 80 | 
| E7  | NULL | 16 | Toyko           | E3  | P2  | 20 | 
| E7  | NULL | 16 | Toyko           | E4  | P2  | NULL | 
| E7  | NULL | 16 | Toyko           | E4  | P4  | 40 | 
| E7  | NULL | 16 | Toyko           | E4  | P5  | 62 | 
| E7  | NULL | 16 | Toyko           | E5  | P7  | 80 | 
| E7  | NULL | 16 | Toyko           | E5  | P5  | NULL | 
| E7  | NULL | 16 | Toyko           | E6  | P1  | 80 | 
| E7  | NULL | 16 | Toyko           | E6  | P3  | NULL | 
| E7  | NULL | 16 | Toyko           | E7  | P7  | 5 | 
| E7  | NULL | 16 | Toyko           | E7  | P1  | 200 | 
| E7  | NULL | 16 | Toyko           | E7  | P5  | 45 | 
| E7  | NULL | 16 | Toyko           | E1  | P5  | 12 | 
| E7  | NULL | 16 | Toyko           | E2  | P1  | 40 | 
| E7  | NULL | 16 | Toyko           | E2  | P2  | 80 | 
| E7  | NULL | 16 | Toyko           | E3  | P2  | 20 | 
| E7  | NULL | 16 | Toyko           | E4  | P2  | NULL | 
| E7  | NULL | 16 | Toyko           | E4  | P4  | 40 | 
| E7  | NULL | 16 | Toyko           | E4  | P5  | 62 | 
| E7  | NULL | 16 | Toyko           | E5  | P7  | 80 | 
| E7  | NULL | 16 | Toyko           | E5  | P7  | 80 | 
| E7  | NULL | 16 | Toyko           | E5  | P5  | NULL | 
| E7  | NULL | 16 | Toyko           | E6  | P1  | 80 | 
| E7  | NULL | 16 | Toyko           | E2  | P1  | 40 | 
| E7  | NULL | 16 | Toyko           | E2  | P2  | 80 | 
| E7  | NULL | 16 | Toyko           | E3  | P2  | 20 | 
| E7  | NULL | 16 | Toyko           | E4  | P2  | NULL | 
| E7  | NULL | 16 | Toyko           | E4  | P4  | 40 | 
| E7  | NULL | 16 | Toyko           | E4  | P5  | 62 | 
| E7  | NULL | 16 | Toyko           | E5  | P7  | 80 | 
| E7  | NULL | 16 | Toyko           | E5  | P7  | 80 | 
| E8  | Lucia                | 20 | NULL | E1  | P1  | 40 | 
| E8  | Lucia                | 20 | NULL | E1  | P2  | 20 | 
| E8  | Lucia                | 20 | NULL | E1  | P3  | 80 | 
| E8  | Lucia                | 20 | NULL | E1  | P4  | 20 | 
| E8  | Lucia                | 20 | NULL | E1  | P5  | 12 | 
| E8  | Lucia                | 20 | NULL | E1  | P6  | 12 | 
| E8  | Lucia                | 20 | NULL | E2  | P1  | 40 | 
| E8  | Lucia                | 20 | NULL | E2  | P2  | 80 | 
| E8  | Lucia                | 20 | NULL | E3  | P2  | 20 | 
| E8  | Lucia                | 20 | NULL | E4  | P2  | NULL | 
| E8  | Lucia                | 20 | NULL | E4  | P4  | 40 | 
| E8  | Lucia                | 20 | NULL | E4  | P5  | 62 | 
| E8  | Lucia                | 20 | NULL | E4  | P6  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P7  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P6  | 150 | 
| E8  | Lucia                | 20 | NULL | E5  | P5  | NULL | 
| E8  | Lucia                | 20 | NULL | E6  | P1  | 80 | 
| E8  | Lucia                | 20 | NULL | E6  | P3  | NULL | 
| E8  | Lucia                | 20 | NULL | E6  | P6  | 100 | 
| E8  | Lucia                | 20 | NULL | E7  | P7  | 5 | 
| E8  | Lucia                | 20 | NULL | E7  | P1  | 200 | 
| E8  | Lucia                | 20 | NULL | E7  | P5  | 45 | 
| E8  | Lucia                | 20 | NULL | E1  | P5  | 12 | 
| E8  | Lucia                | 20 | NULL | E1  | P6  | 12 | 
| E8  | Lucia                | 20 | NULL | E2  | P1  | 40 | 
| E8  | Lucia                | 20 | NULL | E2  | P2  | 80 | 
| E8  | Lucia                | 20 | NULL | E3  | P2  | 20 | 
| E8  | Lucia                | 20 | NULL | E4  | P2  | NULL | 
| E8  | Lucia                | 20 | NULL | E4  | P4  | 40 | 
| E8  | Lucia                | 20 | NULL | E4  | P5  | 62 | 
| E8  | Lucia                | 20 | NULL | E4  | P6  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P7  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P7  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P6  | 150 | 
| E8  | Lucia                | 20 | NULL | E5  | P5  | NULL | 
| E8  | Lucia                | 20 | NULL | E6  | P1  | 80 | 
| E8  | Lucia                | 20 | NULL | E2  | P1  | 40 | 
| E8  | Lucia                | 20 | NULL | E2  | P2  | 80 | 
| E8  | Lucia                | 20 | NULL | E3  | P2  | 20 | 
| E8  | Lucia                | 20 | NULL | E4  | P2  | NULL | 
| E8  | Lucia                | 20 | NULL | E4  | P4  | 40 | 
| E8  | Lucia                | 20 | NULL | E4  | P5  | 62 | 
| E8  | Lucia                | 20 | NULL | E4  | P6  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P7  | 80 | 
| E8  | Lucia                | 20 | NULL | E5  | P7  | 80 | 
| E9  | Frank                | NULL | Toyko           | E1  | P1  | 40 | 
| E9  | Frank                | NULL | Toyko           | E1  | P2  | 20 | 
| E9  | Frank                | NULL | Toyko           | E1  | P3  | 80 | 
| E9  | Frank                | NULL | Toyko           | E1  | P4  | 20 | 
| E9  | Frank                | NULL | Toyko           | E1  | P5  | 12 | 
| E9  | Frank                | NULL | Toyko           | E2  | P1  | 40 | 
| E9  | Frank                | NULL | Toyko           | E2  | P2  | 80 | 
| E9  | Frank                | NULL | Toyko           | E3  | P2  | 20 | 
| E9  | Frank                | NULL | Toyko           | E4  | P2  | NULL | 
| E9  | Frank                | NULL | Toyko           | E4  | P4  | 40 | 
| E9  | Frank                | NULL | Toyko           | E4  | P5  | 62 | 
| E9  | Frank                | NULL | Toyko           | E5  | P7  | 80 | 
| E9  | Frank                | NULL | Toyko           | E5  | P5  | NULL | 
| E9  | Frank                | NULL | Toyko           | E6  | P1  | 80 | 
| E9  | Frank                | NULL | Toyko           | E6  | P3  | NULL | 
| E9  | Frank                | NULL | Toyko           | E7  | P7  | 5 | 
| E9  | Frank                | NULL | Toyko           | E7  | P1  | 200 | 
| E9  | Frank                | NULL | Toyko           | E7  | P5  | 45 | 
| E9  | Frank                | NULL | Toyko           | E1  | P5  | 12 | 
| E9  | Frank                | NULL | Toyko           | E2  | P1  | 40 | 
| E9  | Frank                | NULL | Toyko           | E2  | P2  | 80 | 
| E9  | Frank                | NULL | Toyko           | E3  | P2  | 20 | 
| E9  | Frank                | NULL | Toyko           | E4  | P2  | NULL | 
| E9  | Frank                | NULL | Toyko           | E4  | P4  | 40 | 
| E9  | Frank                | NULL | Toyko           | E4  | P5  | 62 | 
| E9  | Frank                | NULL | Toyko           | E5  | P7  | 80 | 
| E9  | Frank                | NULL | Toyko           | E5  | P7  | 80 | 
| E9  | Frank                | NULL | Toyko           | E5  | P5  | NULL | 
| E9  | Frank                | NULL | Toyko           | E6  | P1  | 80 | 
| E9  | Frank                | NULL | Toyko           | E2  | P1  | 40 | 
| E9  | Frank                | NULL | Toyko           | E2  | P2  | 80 | 
| E9  | Frank                | NULL | Toyko           | E3  | P2  | 20 | 
| E9  | Frank                | NULL | Toyko           | E4  | P2  | NULL | 
| E9  | Frank                | NULL | Toyko           | E4  | P4  | 40 | 
| E9  | Frank                | NULL | Toyko           | E4  | P5  | 62 | 
| E9  | Frank                | NULL | Toyko           | E5  | P7  | 80 | 
| E9  | Frank                | NULL | Toyko           | E5  | P7  | 80 | 
| E10 | NULL | 3 | NULL | E1  | P1  | 40 | 
| E10 | NULL | 3 | NULL | E1  | P2  | 20 | 
| E10 | NULL | 3 | NULL | E1  | P3  | 80 | 
| E10 | NULL | 3 | NULL | E1  | P4  | 20 | 
| E10 | NULL | 3 | NULL | E1  | P5  | 12 | 
| E10 | NULL | 3 | NULL | E1  | P6  | 12 | 
| E10 | NULL | 3 | NULL | E2  | P1  | 40 | 
| E10 | NULL | 3 | NULL | E2  | P2  | 80 | 
| E10 | NULL | 3 | NULL | E3  | P2  | 20 | 
| E10 | NULL | 3 | NULL | E4  | P2  | NULL | 
| E10 | NULL | 3 | NULL | E4  | P4  | 40 | 
| E10 | NULL | 3 | NULL | E4  | P5  | 62 | 
| E10 | NULL | 3 | NULL | E4  | P6  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P7  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P6  | 150 | 
| E10 | NULL | 3 | NULL | E5  | P5  | NULL | 
| E10 | NULL | 3 | NULL | E6  | P1  | 80 | 
| E10 | NULL | 3 | NULL | E6  | P3  | NULL | 
| E10 | NULL | 3 | NULL | E6  | P6  | 100 | 
| E10 | NULL | 3 | NULL | E7  | P7  | 5 | 
| E10 | NULL | 3 | NULL | E7  | P1  | 200 | 
| E10 | NULL | 3 | NULL | E7  | P5  | 45 | 
| E10 | NULL | 3 | NULL | E1  | P5  | 12 | 
| E10 | NULL | 3 | NULL | E1  | P6  | 12 | 
| E10 | NULL | 3 | NULL | E2  | P1  | 40 | 
| E10 | NULL | 3 | NULL | E2  | P2  | 80 | 
| E10 | NULL | 3 | NULL | E3  | P2  | 20 | 
| E10 | NULL | 3 | NULL | E4  | P2  | NULL | 
| E10 | NULL | 3 | NULL | E4  | P4  | 40 | 
| E10 | NULL | 3 | NULL | E4  | P5  | 62 | 
| E10 | NULL | 3 | NULL | E4  | P6  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P7  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P7  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P6  | 150 | 
| E10 | NULL | 3 | NULL | E5  | P5  | NULL | 
| E10 | NULL | 3 | NULL | E6  | P1  | 80 | 
| E10 | NULL | 3 | NULL | E2  | P1  | 40 | 
| E10 | NULL | 3 | NULL | E2  | P2  | 80 | 
| E10 | NULL | 3 | NULL | E3  | P2  | 20 | 
| E10 | NULL | 3 | NULL | E4  | P2  | NULL | 
| E10 | NULL | 3 | NULL | E4  | P4  | 40 | 
| E10 | NULL | 3 | NULL | E4  | P5  | 62 | 
| E10 | NULL | 3 | NULL | E4  | P6  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P7  | 80 | 
| E10 | NULL | 3 | NULL | E5  | P7  | 80 | 
| E11 | James                | 4 | Seoul           | E1  | P1  | 40 | 
| E11 | James                | 4 | Seoul           | E1  | P2  | 20 | 
| E11 | James                | 4 | Seoul           | E1  | P3  | 80 | 
| E11 | James                | 4 | Seoul           | E1  | P4  | 20 | 
| E11 | James                | 4 | Seoul           | E1  | P5  | 12 | 
| E11 | James                | 4 | Seoul           | E1  | P6  | 12 | 
| E11 | James                | 4 | Seoul           | E2  | P1  | 40 | 
| E11 | James                | 4 | Seoul           | E2  | P2  | 80 | 
| E11 | James                | 4 | Seoul           | E3  | P2  | 20 | 
| E11 | James                | 4 | Seoul           | E4  | P2  | NULL | 
| E11 | James                | 4 | Seoul           | E4  | P4  | 40 | 
| E11 | James                | 4 | Seoul           | E4  | P5  | 62 | 
| E11 | James                | 4 | Seoul           | E4  | P6  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P7  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P6  | 150 | 
| E11 | James                | 4 | Seoul           | E5  | P5  | NULL | 
| E11 | James                | 4 | Seoul           | E6  | P1  | 80 | 
| E11 | James                | 4 | Seoul           | E6  | P3  | NULL | 
| E11 | James                | 4 | Seoul           | E6  | P6  | 100 | 
| E11 | James                | 4 | Seoul           | E7  | P7  | 5 | 
| E11 | James                | 4 | Seoul           | E7  | P1  | 200 | 
| E11 | James                | 4 | Seoul           | E7  | P5  | 45 | 
| E11 | James                | 4 | Seoul           | E1  | P5  | 12 | 
| E11 | James                | 4 | Seoul           | E1  | P6  | 12 | 
| E11 | James                | 4 | Seoul           | E2  | P1  | 40 | 
| E11 | James                | 4 | Seoul           | E2  | P2  | 80 | 
| E11 | James                | 4 | Seoul           | E3  | P2  | 20 | 
| E11 | James                | 4 | Seoul           | E4  | P2  | NULL | 
| E11 | James                | 4 | Seoul           | E4  | P4  | 40 | 
| E11 | James                | 4 | Seoul           | E4  | P5  | 62 | 
| E11 | James                | 4 | Seoul           | E4  | P6  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P7  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P7  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P6  | 150 | 
| E11 | James                | 4 | Seoul           | E5  | P5  | NULL | 
| E11 | James                | 4 | Seoul           | E6  | P1  | 80 | 
| E11 | James                | 4 | Seoul           | E2  | P1  | 40 | 
| E11 | James                | 4 | Seoul           | E2  | P2  | 80 | 
| E11 | James                | 4 | Seoul           | E3  | P2  | 20 | 
| E11 | James                | 4 | Seoul           | E4  | P2  | NULL | 
| E11 | James                | 4 | Seoul           | E4  | P4  | 40 | 
| E11 | James                | 4 | Seoul           | E4  | P5  | 62 | 
| E11 | James                | 4 | Seoul           | E4  | P6  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P7  | 80 | 
| E11 | James                | 4 | Seoul           | E5  | P7  | 80 | 
