| 3 | 62 | Vienna          | 
| 1 | 45 | Vienna          | 
| 3 | 80 | Toyko           | 
| 2 | 12 | Vienna          | 
| 7 | 80 | Deale           | 
| 4 | 20 | Vienna          | 
| 2 | 150 | Toyko           | 
| 1 | 5 | Deale           | 
| 1 | 200 | Deale           | 
| 5 | NULL | Vienna          | 
| 3 | 80 | Vienna          | 
| 1 | 100 | Toyko           | 
| 7 | 40 | Deale           | 
| 1 | 20 | Deale           | 
| 2 | 12 | Toyko           | 
