set hive.ql.mode=hql;
drop database IF EXISTS SULLIVAN CASCADE;
create database SULLIVAN;
use SULLIVAN;
CREATE TABLE WORKS_P(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0518/WORKS_P.csv' OVERWRITE INTO TABLE WORKS_P;
CREATE TABLE TTT(P1 DOUBLE,P2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0518/TTT.csv' OVERWRITE INTO TABLE TTT;
SELECT PNUM,PNAME,USER FROM HU.PROJ WHERE PNUM = 'P3';
