set hive.ql.mode=hql;
drop database IF EXISTS SULLIVAN CASCADE;
create database SULLIVAN;
use SULLIVAN;
CREATE TABLE WORKS_P(EMPNUM STRING,PNUM STRING,HOURS DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0520/WORKS_P.csv' OVERWRITE INTO TABLE WORKS_P;
CREATE TABLE TTT(P1 DOUBLE,P2 STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;
LOAD DATA LOCAL INPATH '_datapath_/plusd/0520/TTT.csv' OVERWRITE INTO TABLE TTT;
SELECT EMPNUM,PNUM,USER FROM HU.WORKS WHERE EMPNUM = 'E3';
